// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Empty
	KeySelection
	Address
	Height
	Balances
	Key
	BoolResponse
	NetParams
	TransactionList
	Tx
	Txid
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyPurpose int32

const (
	KeyPurpose_INTERNAL KeyPurpose = 0
	KeyPurpose_EXTERNAL KeyPurpose = 1
)

var KeyPurpose_name = map[int32]string{
	0: "INTERNAL",
	1: "EXTERNAL",
}
var KeyPurpose_value = map[string]int32{
	"INTERNAL": 0,
	"EXTERNAL": 1,
}

func (x KeyPurpose) String() string {
	return proto.EnumName(KeyPurpose_name, int32(x))
}
func (KeyPurpose) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type KeySelection struct {
	Purpose KeyPurpose `protobuf:"varint,1,opt,name=purpose,enum=pb.KeyPurpose" json:"purpose,omitempty"`
}

func (m *KeySelection) Reset()                    { *m = KeySelection{} }
func (m *KeySelection) String() string            { return proto.CompactTextString(m) }
func (*KeySelection) ProtoMessage()               {}
func (*KeySelection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeySelection) GetPurpose() KeyPurpose {
	if m != nil {
		return m.Purpose
	}
	return KeyPurpose_INTERNAL
}

type Address struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Address) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Height struct {
	Height uint32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *Height) Reset()                    { *m = Height{} }
func (m *Height) String() string            { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()               {}
func (*Height) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Height) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Balances struct {
	Confirmed   uint64 `protobuf:"varint,1,opt,name=confirmed" json:"confirmed,omitempty"`
	Unconfirmed uint64 `protobuf:"varint,2,opt,name=unconfirmed" json:"unconfirmed,omitempty"`
}

func (m *Balances) Reset()                    { *m = Balances{} }
func (m *Balances) String() string            { return proto.CompactTextString(m) }
func (*Balances) ProtoMessage()               {}
func (*Balances) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Balances) GetConfirmed() uint64 {
	if m != nil {
		return m.Confirmed
	}
	return 0
}

func (m *Balances) GetUnconfirmed() uint64 {
	if m != nil {
		return m.Unconfirmed
	}
	return 0
}

type Key struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type BoolResponse struct {
	Bool bool `protobuf:"varint,1,opt,name=bool" json:"bool,omitempty"`
}

func (m *BoolResponse) Reset()                    { *m = BoolResponse{} }
func (m *BoolResponse) String() string            { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()               {}
func (*BoolResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BoolResponse) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

type NetParams struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NetParams) Reset()                    { *m = NetParams{} }
func (m *NetParams) String() string            { return proto.CompactTextString(m) }
func (*NetParams) ProtoMessage()               {}
func (*NetParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NetParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TransactionList struct {
	Transactions []*Tx `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionList) Reset()                    { *m = TransactionList{} }
func (m *TransactionList) String() string            { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()               {}
func (*TransactionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TransactionList) GetTransactions() []*Tx {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Tx struct {
	Txid      string                     `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Value     int64                      `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Height    int32                      `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	WatchOnly bool                       `protobuf:"varint,5,opt,name=watchOnly" json:"watchOnly,omitempty"`
	Raw       []byte                     `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Tx) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Tx) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Tx) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Tx) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Tx) GetWatchOnly() bool {
	if m != nil {
		return m.WatchOnly
	}
	return false
}

func (m *Tx) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type Txid struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *Txid) Reset()                    { *m = Txid{} }
func (m *Txid) String() string            { return proto.CompactTextString(m) }
func (*Txid) ProtoMessage()               {}
func (*Txid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Txid) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*KeySelection)(nil), "pb.KeySelection")
	proto.RegisterType((*Address)(nil), "pb.Address")
	proto.RegisterType((*Height)(nil), "pb.Height")
	proto.RegisterType((*Balances)(nil), "pb.Balances")
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*BoolResponse)(nil), "pb.BoolResponse")
	proto.RegisterType((*NetParams)(nil), "pb.NetParams")
	proto.RegisterType((*TransactionList)(nil), "pb.TransactionList")
	proto.RegisterType((*Tx)(nil), "pb.Tx")
	proto.RegisterType((*Txid)(nil), "pb.Txid")
	proto.RegisterEnum("pb.KeyPurpose", KeyPurpose_name, KeyPurpose_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	CurrentAddress(ctx context.Context, in *KeySelection, opts ...grpc.CallOption) (*Address, error)
	NewAddress(ctx context.Context, in *KeySelection, opts ...grpc.CallOption) (*Address, error)
	ChainTip(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Height, error)
	Balance(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Balances, error)
	MasterPrivateKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Key, error)
	MasterPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Key, error)
	HasKey(ctx context.Context, in *Address, opts ...grpc.CallOption) (*BoolResponse, error)
	Params(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetParams, error)
	Transactions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransactionList, error)
	GetTransaction(ctx context.Context, in *Txid, opts ...grpc.CallOption) (*Tx, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.API/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CurrentAddress(ctx context.Context, in *KeySelection, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := grpc.Invoke(ctx, "/pb.API/CurrentAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) NewAddress(ctx context.Context, in *KeySelection, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := grpc.Invoke(ctx, "/pb.API/NewAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ChainTip(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Height, error) {
	out := new(Height)
	err := grpc.Invoke(ctx, "/pb.API/ChainTip", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Balance(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Balances, error) {
	out := new(Balances)
	err := grpc.Invoke(ctx, "/pb.API/Balance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) MasterPrivateKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := grpc.Invoke(ctx, "/pb.API/MasterPrivateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) MasterPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := grpc.Invoke(ctx, "/pb.API/MasterPublicKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) HasKey(ctx context.Context, in *Address, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := grpc.Invoke(ctx, "/pb.API/HasKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Params(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetParams, error) {
	out := new(NetParams)
	err := grpc.Invoke(ctx, "/pb.API/Params", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Transactions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TransactionList, error) {
	out := new(TransactionList)
	err := grpc.Invoke(ctx, "/pb.API/Transactions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetTransaction(ctx context.Context, in *Txid, opts ...grpc.CallOption) (*Tx, error) {
	out := new(Tx)
	err := grpc.Invoke(ctx, "/pb.API/GetTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Stop(context.Context, *Empty) (*Empty, error)
	CurrentAddress(context.Context, *KeySelection) (*Address, error)
	NewAddress(context.Context, *KeySelection) (*Address, error)
	ChainTip(context.Context, *Empty) (*Height, error)
	Balance(context.Context, *Empty) (*Balances, error)
	MasterPrivateKey(context.Context, *Empty) (*Key, error)
	MasterPublicKey(context.Context, *Empty) (*Key, error)
	HasKey(context.Context, *Address) (*BoolResponse, error)
	Params(context.Context, *Empty) (*NetParams, error)
	Transactions(context.Context, *Empty) (*TransactionList, error)
	GetTransaction(context.Context, *Txid) (*Tx, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CurrentAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeySelection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CurrentAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/CurrentAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CurrentAddress(ctx, req.(*KeySelection))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_NewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeySelection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).NewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/NewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).NewAddress(ctx, req.(*KeySelection))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/ChainTip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ChainTip(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Balance(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_MasterPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).MasterPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/MasterPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).MasterPrivateKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_MasterPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).MasterPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/MasterPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).MasterPublicKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_HasKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).HasKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/HasKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).HasKey(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Params(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Transactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Transactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/Transactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Transactions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Txid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.API/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetTransaction(ctx, req.(*Txid))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _API_Stop_Handler,
		},
		{
			MethodName: "CurrentAddress",
			Handler:    _API_CurrentAddress_Handler,
		},
		{
			MethodName: "NewAddress",
			Handler:    _API_NewAddress_Handler,
		},
		{
			MethodName: "ChainTip",
			Handler:    _API_ChainTip_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _API_Balance_Handler,
		},
		{
			MethodName: "MasterPrivateKey",
			Handler:    _API_MasterPrivateKey_Handler,
		},
		{
			MethodName: "MasterPublicKey",
			Handler:    _API_MasterPublicKey_Handler,
		},
		{
			MethodName: "HasKey",
			Handler:    _API_HasKey_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _API_Params_Handler,
		},
		{
			MethodName: "Transactions",
			Handler:    _API_Transactions_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _API_GetTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xed, 0x3a, 0x71, 0x92, 0x89, 0x9b, 0x46, 0xfb, 0xff, 0x0b, 0x22, 0x0b, 0xa8, 0xb5,
	0x20, 0x61, 0x2a, 0x91, 0x42, 0xb8, 0xf4, 0xc2, 0xa1, 0xad, 0x2a, 0x5a, 0x5a, 0x42, 0xe4, 0xfa,
	0xc0, 0x75, 0x13, 0x6f, 0x9b, 0x15, 0x8e, 0xd7, 0xda, 0xdd, 0xb4, 0xcd, 0x5b, 0xf1, 0x24, 0x3c,
	0x13, 0xda, 0xb5, 0x1d, 0x3b, 0x07, 0x24, 0x6e, 0xdf, 0xce, 0x7c, 0x1e, 0x7d, 0x33, 0xfe, 0x41,
	0x8f, 0xe4, 0x6c, 0x9c, 0x0b, 0xae, 0x38, 0xda, 0xcb, 0xe7, 0xfe, 0xe1, 0x3d, 0xe7, 0xf7, 0x29,
	0x3d, 0x36, 0x95, 0xf9, 0xfa, 0xee, 0x58, 0xb1, 0x15, 0x95, 0x8a, 0xac, 0xf2, 0xc2, 0x84, 0x3b,
	0xd0, 0xbe, 0x58, 0xe5, 0x6a, 0x83, 0x4f, 0xc0, 0xbb, 0xa6, 0x9b, 0x5b, 0x9a, 0xd2, 0x85, 0x62,
	0x3c, 0x43, 0x21, 0x74, 0xf2, 0xb5, 0xc8, 0xb9, 0xa4, 0x23, 0x3b, 0xb0, 0xc3, 0xc1, 0x64, 0x30,
	0xce, 0xe7, 0xe3, 0x6b, 0xba, 0x99, 0x15, 0xd5, 0xa8, 0x6a, 0xe3, 0x97, 0xd0, 0x39, 0x4d, 0x12,
	0x41, 0xa5, 0x44, 0x08, 0x5a, 0x24, 0x49, 0x84, 0xf9, 0xa2, 0x17, 0x19, 0x8d, 0x03, 0x70, 0x2f,
	0x29, 0xbb, 0x5f, 0x2a, 0xf4, 0x0c, 0xdc, 0xa5, 0x51, 0xa6, 0xbf, 0x1f, 0x95, 0x2f, 0xfc, 0x15,
	0xba, 0x67, 0x24, 0x25, 0xd9, 0x82, 0x4a, 0xf4, 0x02, 0x7a, 0x0b, 0x9e, 0xdd, 0x31, 0xb1, 0xa2,
	0x89, 0xb1, 0xb5, 0xa2, 0xba, 0x80, 0x02, 0xe8, 0xaf, 0xb3, 0xba, 0xbf, 0x67, 0xfa, 0xcd, 0x12,
	0x7e, 0x0e, 0xce, 0x35, 0xdd, 0xa0, 0x21, 0x38, 0x3f, 0xe9, 0xa6, 0xcc, 0xa1, 0x25, 0xc6, 0xe0,
	0x9d, 0x71, 0x9e, 0x46, 0x54, 0xe6, 0x3c, 0x93, 0x54, 0x47, 0x9d, 0x73, 0x9e, 0x1a, 0x4b, 0x37,
	0x32, 0x1a, 0x1f, 0x42, 0x6f, 0x4a, 0xd5, 0x8c, 0x08, 0xb2, 0x32, 0xbb, 0x64, 0x64, 0x45, 0xab,
	0x5d, 0xb4, 0xc6, 0x9f, 0xe1, 0x20, 0x16, 0x24, 0x93, 0xc4, 0xdc, 0xe8, 0x86, 0x49, 0x85, 0x8e,
	0xc0, 0x53, 0x75, 0x49, 0x8e, 0xec, 0xc0, 0x09, 0xfb, 0x13, 0x57, 0x1f, 0x2b, 0x7e, 0x8a, 0x76,
	0x7a, 0xf8, 0x97, 0x0d, 0x7b, 0xf1, 0x93, 0x9e, 0xac, 0x9e, 0x58, 0x52, 0x4d, 0xd6, 0x1a, 0xfd,
	0x0f, 0xed, 0x07, 0x92, 0xae, 0xa9, 0xd9, 0xc9, 0x89, 0x8a, 0x47, 0xe3, 0x62, 0x4e, 0x60, 0x87,
	0xed, 0xea, 0x62, 0xe8, 0x04, 0x7a, 0xdb, 0x1f, 0x39, 0x6a, 0x05, 0x76, 0xd8, 0x9f, 0xf8, 0xe3,
	0xe2, 0x57, 0x8f, 0xab, 0x5f, 0x3d, 0x8e, 0x2b, 0x47, 0x54, 0x9b, 0xf5, 0x7d, 0x1f, 0x89, 0x5a,
	0x2c, 0xbf, 0x67, 0xe9, 0x66, 0xd4, 0x36, 0xbb, 0xd7, 0x05, 0x7d, 0x36, 0x41, 0x1e, 0x47, 0x6e,
	0x60, 0x87, 0x5e, 0xa4, 0x25, 0xf6, 0xa1, 0x15, 0xeb, 0x7c, 0x08, 0x5a, 0x4b, 0x22, 0x97, 0x55,
	0x66, 0xad, 0x8f, 0x42, 0x80, 0x9a, 0x07, 0xe4, 0x41, 0xf7, 0x6a, 0x1a, 0x5f, 0x44, 0xd3, 0xd3,
	0x9b, 0xa1, 0xa5, 0x5f, 0x17, 0x3f, 0xca, 0x97, 0x3d, 0xf9, 0xed, 0x80, 0x73, 0x3a, 0xbb, 0x42,
	0xaf, 0xa0, 0x75, 0xab, 0x78, 0x8e, 0x7a, 0xfa, 0x3c, 0x86, 0x3b, 0xbf, 0x96, 0xd8, 0x42, 0x1f,
	0x61, 0x70, 0xbe, 0x16, 0x82, 0x66, 0xaa, 0x22, 0x6a, 0x58, 0x52, 0xb7, 0x05, 0xd3, 0xef, 0xeb,
	0x4a, 0xd9, 0xc6, 0x16, 0x7a, 0x0f, 0x30, 0xa5, 0x8f, 0xff, 0x6c, 0x7f, 0x0d, 0xdd, 0xf3, 0x25,
	0x61, 0x59, 0xcc, 0x76, 0x52, 0x80, 0x96, 0x05, 0xa6, 0xd8, 0x42, 0x6f, 0xa0, 0x53, 0x02, 0xd9,
	0xf4, 0x78, 0x5a, 0x56, 0xa0, 0x62, 0x0b, 0x85, 0x30, 0xfc, 0x46, 0xa4, 0xa2, 0x62, 0x26, 0xd8,
	0x03, 0x51, 0x54, 0x73, 0xd7, 0xb0, 0x77, 0xca, 0x28, 0xd8, 0x42, 0x6f, 0xe1, 0xa0, 0x74, 0xae,
	0xe7, 0x29, 0x5b, 0xfc, 0xdd, 0xf8, 0x0e, 0xdc, 0x4b, 0x22, 0x75, 0xbf, 0x19, 0xdb, 0x37, 0x5b,
	0x35, 0xe9, 0x35, 0x19, 0xdd, 0x12, 0xd4, 0xc6, 0xa8, 0x7d, 0x2d, 0xb7, 0x08, 0x63, 0x0b, 0x7d,
	0x00, 0xaf, 0x01, 0xec, 0x8e, 0xf7, 0x3f, 0x83, 0xe8, 0x2e, 0xcd, 0x66, 0xee, 0xe0, 0x0b, 0x55,
	0x8d, 0x3a, 0xea, 0x16, 0x2c, 0xb3, 0xc4, 0x2f, 0xa9, 0xc6, 0xd6, 0xdc, 0x35, 0x94, 0x7d, 0xfa,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x3f, 0x32, 0x86, 0x6f, 0x04, 0x00, 0x00,
}
